In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3])

In [3]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)

In [4]:
a

array([1, 2, 3])

In [5]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
c=np.array([[(1.5,2,3),(4,5,6)], [(3,2,1),(4,5,6)]],dtype=float)

In [8]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [11]:
d=np.zeros((3,4))

In [12]:
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
p = np.ones((2, 3, 4))


In [17]:
p

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
p = np.ones((2, 3, 4), dtype=np.int16)

In [19]:
p

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
e=np.array((10,25,5))

In [22]:
e

array([10, 25,  5])

In [25]:
np.linspace(0, 2, 9)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
v=np.linspace(2, 2, 7)


In [29]:
v

array([2., 2., 2., 2., 2., 2., 2.])

In [38]:
v


array([2., 2., 2., 2., 2., 2., 2.])

In [30]:
x=np.linspace(2, 2, 7)

In [31]:
x

array([2., 2., 2., 2., 2., 2., 2.])

In [33]:
i=np.eye(2)

In [34]:
i

array([[1., 0.],
       [0., 1.]])

In [36]:
r=np.random.rand(2,2)

In [37]:
r

array([[0.2958029 , 0.95651173],
       [0.0102737 , 0.25862752]])

In [39]:
print("a -> shape:" ,a.shape, "ndim:", a.ndim, "size:", a.size)

a -> shape: (3,) ndim: 1 size: 3


In [40]:
print("b -> shape:" ,b.shape, "ndim:", b.ndim, "size:", b.size)

b -> shape: (2, 3) ndim: 2 size: 6


In [41]:
print("c -> shape:" ,c.shape, "ndim:", c.ndim, "size:", c.size)

c -> shape: (2, 2, 3) ndim: 3 size: 12


In [43]:
print("b dtype:" , b.dtype)
print("b dtype:" , b.dtype.name)
b_int=b.astype(int)
print("b converted to int :\n", b_int)

b dtype: float64
b dtype: float64
b converted to int :
 [[1 2 3]
 [4 5 6]]


In [49]:
print("b * b:\n", b*b)

b * b:
 [[ 2.25  4.    9.  ]
 [16.   25.   36.  ]]


In [50]:
print("b * b:\n", b/b)

b * b:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [51]:
b=np.sqrt(b)

In [52]:
b

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [72]:
m=np.array([1,9,6])


In [73]:
np.sum(m)

16

In [74]:
np.min(m)

1

In [75]:
np.median(m)

6.0

In [76]:
np.mean(m)


5.333333333333333

In [77]:
np.cumsum(m)



array([ 1, 10, 16])

In [78]:
np.std(m)


3.2998316455372216